<?php

namespace AppBundle\Repository;

/**
 * DutyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DutyRepository extends \Doctrine\ORM\EntityRepository
{
}
